all:
  vars:
    control_plane_endpoint: 192.168.43.100
    load_balancer_ip_pool:
      - 192.168.43.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.43.110, mac: 'e8:6a:64:a5:93:6a', disk: nvme0n1, network_interface: eno2}
